version: '3'
services:
  # app:
  #   container_name: app
  #   build:
  #     context: .
  #     dockerfile: DockerFile.base
  #   depends_on:
  #     - db
  #   environment:
  #     - SERVER_ENV=development
  #   command: tail -f /dev/null
  #   ports:
  #     - "3333:3333"
  #     - "80:80"
  #   volumes:
  #     - ${PWD}/:/code
  #     - ${PWD}/storage/logs:/tmp/logs
  db:
    image: postgres:15.0
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: db
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=rabbitmq
        - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
